### ISSUE TITLE
Are UI orientations supported? 

### ISSUE THREAD

**Issue by cclaan** [duraidabdul/LocalConsole#10]
Thanks for creating this useful library. I tested on an iPad app but the UI seems locked in portrait mode. Is there some way to enable auto rotation?

**Comment by duraidabdul** [comment]
Currently auto-rotate isn't supported but I'm planning to add support for it in the future! Thanks for the feature request 😃

**Comment by cclaan** [comment]
Thanks for replying. Does it seem like a simple thing to add? I haven't looked into the code, but if it's something like setting a few view controller properties then I can try doing that.

**Comment by duraidabdul** [comment]
It's not quite that simple, I will have to add support for saving the console's last position correctly in both portrait and landscape, and I will have to come up with a new layout for the Resize Console view.

**Comment by duraidabdul** [comment]
Orientations have been added now, thanks for your feedback!
