### ISSUE TITLE
freezing after many logs 

### ISSUE THREAD

**Issue by moyoteg** [duraidabdul/LocalConsole#12]
First off, awesome job!

**Comment by moyoteg** [comment]
Secondly, for some reason when a bunch of logs have been sent to the console the application freezes. 🤷‍♂️

**Comment by duraidabdul** [comment]
Do you have an approximate line count when it starts to hitch/freeze? I found that it takes a while to print logs when it reaches around 15,000 - 30,000 lines of text.

I will work on a fix when I get the chance!

**Comment by moyoteg** [comment]
I am not sure when it starts to freeze, but probably using a "reusable" cell type solution would get rid of the issue all together. Would you like help to figure it out? 😄
