### ISSUE TITLE
Cannot compile with Xcode 13 anymore

### ISSUE THREAD

**Issue by murphy2712** [duraidabdul/LocalConsole#14]
<img width="977" alt="image" src="https://user-images.githubusercontent.com/712327/191214273-081d952a-af0e-42c6-867e-cc89f5ebc377.png">

The error comes in this line:
`guard let consoleWindow else { return [] }`

"Variable binding in a condition requires an initializer"

**Comment by duraidabdul** [comment]
Thank you for bringing this up, it is now fixed!

**Comment by murphy2712** [comment]
Thanks for the quick fix!
