### ISSUE TITLE
Input blocked on iPads without home button

### ISSUE THREAD

**Issue by moorea** [duraidabdul/LocalConsole#17]
When running on an iPad or iPad simulator that has no home button, if `LCManager.shared.isVisible` is `true`, all other input seems to be blocked. Touches don't get passed down.

Did a bit of debugging and it seems that when running on an iPad with no home button, the `ConsoleWindow` [hit test](https://github.com/duraidabdul/LocalConsole/blob/main/Sources/LocalConsole/LCManager.swift#L1186) will return a View when we're not expecting it to (would be expecting that function to be returning `nil`).

It's unclear to me why this would behave differently on different iPads, but maybe this makes sense to someone smarter than me?

**Comment by duraidabdul** [comment]
Thank you for the report 😃 This is now fixed!

**Comment by moorea** [comment]
Thanks for taking a look! This is a great component you've built. Very handy 💯
