### ISSUE TITLE
No longer visible above presented view controllers

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [duraidabdul/LocalConsole#18]
Version 1.11.0 causes the console to no longer sit on top of presented view controllers. Also when you tap the more menu you get:

> [Presentation] Presenting view controller <_UIContextMenuActionsOnlyViewController: 0x7fb2bf605470> from detached view controller <LocalConsole.ConsoleViewController: 0x7fb2be27ecb0> is discouraged.

**Comment by jordanhbuiltbyhq** [comment]
![Simulator Screen Shot - iPhone 14 Pro - 2022-10-19 at 10 25 47](https://user-images.githubusercontent.com/15804476/196749989-733b3b58-15bb-4af1-bf0b-8f8aa50ead30.png)

**Comment by duraidabdul** [comment]
Thank you for the report, these issues should be fixed now! Please let me know if it's working as expected 🙂

**Comment by jordanhbuiltbyhq** [comment]
Confirmed thank you
