### ISSUE TITLE
UI API called on a Main thread? -(Crash)

### ISSUE THREAD

**Issue by moyoteg** [duraidabdul/LocalConsole#4]
Seems like there is an issue 😄:

`=================================================================
Main Thread Checker: UI API called on a background thread: -[UIScrollView contentOffset]
PID: 6701, TID: 2996419, Thread name: (none), Queue name: NSOperationQueue 0x7f8685ca3840 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   ***** *****                        0x0000000104fdf804 $s12LocalConsole9LCManagerC5printyyypF + 164
5   ***** *****                        0x0000000104ae715b $s10CloudyLogs6LoggerC3log_4typeySS_ypSgtFZ + 235
6   ***** *****                        0x0000000104edeb3d $s6Shared6*****O13CommunicationEADC14attemptToQueue7channelSo16NSBlockOperationCSgAE7ChannelO_tFyycfU2_ + 477
7   ***** *****                        0x0000000104ede7c0 $sIeg_IeyB_TR + 48
8   Foundation                          0x00007fff207fa0be __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
9   Foundation                          0x00007fff207f9fb6 -[NSBlockOperation main] + 98
10  Foundation                          0x00007fff207fcfd2 __NSOPERATION_IS_INVOKING_MAIN__ + 17
11  Foundation                          0x00007fff207f9200 -[NSOperation start] + 785
12  Foundation                          0x00007fff207fd947 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
13  Foundation                          0x00007fff207fd46a __NSOQSchedule_f + 182
14  libdispatch.dylib                   0x000000010635e2c5 _dispatch_block_async_invoke2 + 83
15  libdispatch.dylib                   0x000000010634f74e _dispatch_client_callout + 8
16  libdispatch.dylib                   0x0000000106352066 _dispatch_continuation_pop + 557
17  libdispatch.dylib                   0x000000010635147b _dispatch_async_redirect_invoke + 770
18  libdispatch.dylib                   0x00000001063611b0 _dispatch_root_queue_drain + 351
19  libdispatch.dylib                   0x0000000106361b0f _dispatch_worker_thread2 + 135
20  libsystem_pthread.dylib             0x00007fff60340417 _pthread_wqthread + 244
21  libsystem_pthread.dylib             0x00007fff6033f42f start_wqthread + 15
2021-06-21 18:01:24.765790-0500 ***** *****[6701:2996419] [reports] Main Thread Checker: UI API called on a background thread: -[UIScrollView contentOffset]
PID: 6701, TID: 2996419, Thread name: (none), Queue name: NSOperationQueue 0x7f8685ca3840 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   ***** *****                        0x0000000104fdf804 $s12LocalConsole9LCManagerC5printyyypF + 164
5   ***** *****                        0x0000000104ae715b $s10CloudyLogs6LoggerC3log_4typeySS_ypSgtFZ + 235
6   ***** *****                        0x0000000104edeb3d $s6Shared6*****O13CommunicationEADC14attemptToQueue7channelSo16NSBlockOperationCSgAE7ChannelO_tFyycfU2_ + 477
7   ***** *****                        0x0000000104ede7c0 $sIeg_IeyB_TR + 48
8   Foundation                          0x00007fff207fa0be __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
9   Foundation                          0x00007fff207f9fb6 -[NSBlockOperation main] + 98
10  Foundation                          0x00007fff207fcfd2 __NSOPERATION_IS_INVOKING_MAIN__ + 17
11  Foundation                          0x00007fff207f9200 -[NSOperation start] + 785
12  Foundation                          0x00007fff207fd947 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
13  Foundation                          0x00007fff207fd46a __NSOQSchedule_f + 182
14  libdispatch.dylib                   0x000000010635e2c5 _dispatch_block_async_invoke2 + 83
15  libdispatch.dylib                   0x000000010634f74e _dispatch_client_callout + 8
16  libdispatch.dylib                   0x0000000106352066 _dispatch_continuation_pop + 557
17  libdispatch.dylib                   0x000000010635147b _dispatch_async_redirect_invoke + 770
18  libdispatch.dylib                   0x00000001063611b0 _dispatch_root_queue_drain + 351
19  libdispatch.dylib                   0x0000000106361b0f _dispatch_worker_thread2 + 135
20  libsystem_pthread.dylib             0x00007fff60340417 _pthread_wqthread + 244
21  libsystem_pthread.dylib             0x00007fff6033f42f start_wqthread + 15
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIScrollView contentSize]
PID: 6701, TID: 2996419, Thread name: (none), Queue name: NSOperationQueue 0x7f8685ca3840 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   ***** *****                        0x0000000104fe9ca1 $s12LocalConsole16InvertedTextViewC11contentSizeSo6CGSizeVvg + 81
5   ***** *****                        0x0000000104fe9c18 $s12LocalConsole16InvertedTextViewC11contentSizeSo6CGSizeVvgTo + 40
6   ***** *****                        0x0000000104fdf860 $s12LocalConsole9LCManagerC5printyyypF + 256
7   ***** *****                        0x0000000104ae715b $s10CloudyLogs6LoggerC3log_4typeySS_ypSgtFZ + 235
8   ***** *****                        0x0000000104edeb3d $s6Shared6*****O13CommunicationEADC14attemptToQueue7channelSo16NSBlockOperationCSgAE7ChannelO_tFyycfU2_ + 477
9   ***** *****                        0x0000000104ede7c0 $sIeg_IeyB_TR + 48
10  Foundation                          0x00007fff207fa0be __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
11  Foundation                          0x00007fff207f9fb6 -[NSBlockOperation main] + 98
12  Foundation                          0x00007fff207fcfd2 __NSOPERATION_IS_INVOKING_MAIN__ + 17
13  Foundation                          0x00007fff207f9200 -[NSOperation start] + 785
14  Foundation                          0x00007fff207fd947 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
15  Foundation                          0x00007fff207fd46a __NSOQSchedule_f + 182
16  libdispatch.dylib                   0x000000010635e2c5 _dispatch_block_async_invoke2 + 83
17  libdispatch.dylib                   0x000000010634f74e _dispatch_client_callout + 8
18  libdispatch.dylib                   0x0000000106352066 _dispatch_continuation_pop + 557
19  libdispatch.dylib                   0x000000010635147b _dispatch_async_redirect_invoke + 770
20  libdispatch.dylib                   0x00000001063611b0 _dispatch_root_queue_drain + 351
21  libdispatch.dylib                   0x0000000106361b0f _dispatch_worker_thread2 + 135
22  libsystem_pthread.dylib             0x00007fff60340417 _pthread_wqthread + 244
23  libsystem_pthread.dylib             0x00007fff6033f42f start_wqthread + 15
2021-06-21 18:01:24.845531-0500 ***** *****[6701:2996419] [reports] Main Thread Checker: UI API called on a background thread: -[UIScrollView contentSize]
PID: 6701, TID: 2996419, Thread name: (none), Queue name: NSOperationQueue 0x7f8685ca3840 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   ***** *****                        0x0000000104fe9ca1 $s12LocalConsole16InvertedTextViewC11contentSizeSo6CGSizeVvg + 81
5   ***** *****                        0x0000000104fe9c18 $s12LocalConsole16InvertedTextViewC11contentSizeSo6CGSizeVvgTo + 40
6   ***** *****                        0x0000000104fdf860 $s12LocalConsole9LCManagerC5printyyypF + 256
7   ***** *****                        0x0000000104ae715b $s10CloudyLogs6LoggerC3log_4typeySS_ypSgtFZ + 235
8   ***** *****                        0x0000000104edeb3d $s6Shared6*****O13CommunicationEADC14attemptToQueue7channelSo16NSBlockOperationCSgAE7ChannelO_tFyycfU2_ + 477
9   ***** *****                        0x0000000104ede7c0 $sIeg_IeyB_TR + 48
10  Foundation                          0x00007fff207fa0be __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
11  Foundation                          0x00007fff207f9fb6 -[NSBlockOperation main] + 98
12  Foundation                          0x00007fff207fcfd2 __NSOPERATION_IS_INVOKING_MAIN__ + 17
13  Foundation                          0x00007fff207f9200 -[NSOperation start] + 785
14  Foundation                          0x00007fff207fd947 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
15  Foundation                          0x00007fff207fd46a __NSOQSchedule_f + 182
16  libdispatch.dylib                   0x000000010635e2c5 _dispatch_block_async_invoke2 + 83
17  libdispatch.dylib                   0x000000010634f74e _dispatch_client_callout + 8
18  libdispatch.dylib                   0x0000000106352066 _dispatch_continuation_pop + 557
19  libdispatch.dylib                   0x000000010635147b _dispatch_async_redirect_invoke + 770
20  libdispatch.dylib                   0x00000001063611b0 _dispatch_root_queue_drain + 351
21  libdispatch.dylib                   0x0000000106361b0f _dispatch_worker_thread2 + 135
22  libsystem_pthread.dylib             0x00007fff60340417 _pthread_wqthread + 244
23  libsystem_pthread.dylib             0x00007fff6033f42f start_wqthread + 15
2021-06-21 23:01:24 +0000: Communication: service: 📶 ***** BLE: "1-604417" unitIdentifier: 13 not connected, will try to connect
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 6701, TID: 2996419, Thread name: (none), Queue name: NSOperationQueue 0x7f8685ca3840 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   ***** *****                        0x0000000104fdf8e6 $s12LocalConsole9LCManagerC5printyyypF + 390
5   ***** *****                        0x0000000104ae715b $s10CloudyLogs6LoggerC3log_4typeySS_ypSgtFZ + 235
6   ***** *****                        0x0000000104edeb3d $s6Shared6*****O13CommunicationEADC14attemptToQueue7channelSo16NSBlockOperationCSgAE7ChannelO_tFyycfU2_ + 477
7   ***** *****                        0x0000000104ede7c0 $sIeg_IeyB_TR + 48
8   Foundation                          0x00007fff207fa0be __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
9   Foundation                          0x00007fff207f9fb6 -[NSBlockOperation main] + 98
10  Foundation                          0x00007fff207fcfd2 __NSOPERATION_IS_INVOKING_MAIN__ + 17
11  Foundation                          0x00007fff207f9200 -[NSOperation start] + 785
12  Foundation                          0x00007fff207fd947 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
13  Foundation                          0x00007fff207fd46a __NSOQSchedule_f + 182
14  libdispatch.dylib                   0x000000010635e2c5 _dispatch_block_async_invoke2 + 83
15  libdispatch.dylib                   0x000000010634f74e _dispatch_client_callout + 8
16  libdispatch.dylib                   0x0000000106352066 _dispatch_continuation_pop + 557
17  libdispatch.dylib                   0x000000010635147b _dispatch_async_redirect_invoke + 770
18  libdispatch.dylib                   0x00000001063611b0 _dispatch_root_queue_drain + 351
19  libdispatch.dylib                   0x0000000106361b0f _dispatch_worker_thread2 + 135
20  libsystem_pthread.dylib             0x00007fff60340417 _pthread_wqthread + 244
21  libsystem_pthread.dylib             0x00007fff6033f42f start_wqthread + 15
2021-06-21 18:01:24.888052-0500 ***** *****[6701:2996419] [reports] Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 6701, TID: 2996419, Thread name: (none), Queue name: NSOperationQueue 0x7f8685ca3840 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   ***** *****                        0x0000000104fdf8e6 $s12LocalConsole9LCManagerC5printyyypF + 390
5   ***** *****                        0x0000000104ae715b $s10CloudyLogs6LoggerC3log_4typeySS_ypSgtFZ + 235
6   ***** *****                        0x0000000104edeb3d $s6Shared6*****O13CommunicationEADC14attemptToQueue7channelSo16NSBlockOperationCSgAE7ChannelO_tFyycfU2_ + 477
7   ***** *****                        0x0000000104ede7c0 $sIeg_IeyB_TR + 48
8   Foundation                          0x00007fff207fa0be __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
9   Foundation                          0x00007fff207f9fb6 -[NSBlockOperation main] + 98
10  Foundation                          0x00007fff207fcfd2 __NSOPERATION_IS_INVOKING_MAIN__ + 17
11  Foundation                          0x00007fff207f9200 -[NSOperation start] + 785
12  Foundation                          0x00007fff207fd947 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
13  Foundation                          0x00007fff207fd46a __NSOQSchedule_f + 182
14  libdispatch.dylib                   0x000000010635e2c5 _dispatch_block_async_invoke2 + 83
15  libdispatch.dylib                   0x000000010634f74e _dispatch_client_callout + 8
16  libdispatch.dylib                   0x0000000106352066 _dispatch_continuation_pop + 557
17  libdispatch.dylib                   0x000000010635147b _dispatch_async_redirect_invoke + 770
18  libdispatch.dylib                   0x00000001063611b0 _dispatch_root_queue_drain + 351
19  libdispatch.dylib                   0x0000000106361b0f _dispatch_worker_thread2 + 135
20  libsystem_pthread.dylib             0x00007fff60340417 _pthread_wqthread + 244
21  libsystem_pthread.dylib             0x00007fff6033f42f start_wqthread + 15
=================================================================
Main Thread Checker: UI API called on a background thread: -[UITextView text]
PID: 6701, TID: 2996419, Thread name: (none), Queue name: NSOperationQueue 0x7f8685ca3840 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   ***** *****                        0x0000000104fdfbba $s12LocalConsole9LCManagerC5printyyypFSSyXEfU_ + 202
5   ***** *****                        0x0000000104fdf9f9 $s12LocalConsole9LCManagerC5printyyypF + 665
6   ***** *****                        0x0000000104ae715b $s10CloudyLogs6LoggerC3log_4typeySS_ypSgtFZ + 235
7   ***** *****                        0x0000000104edeb3d $s6Shared6*****O13CommunicationEADC14attemptToQueue7channelSo16NSBlockOperationCSgAE7ChannelO_tFyycfU2_ + 477
8   ***** *****                        0x0000000104ede7c0 $sIeg_IeyB_TR + 48
9   Foundation                          0x00007fff207fa0be __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
10  Foundation                          0x00007fff207f9fb6 -[NSBlockOperation main] + 98
11  Foundation                          0x00007fff207fcfd2 __NSOPERATION_IS_INVOKING_MAIN__ + 17
12  Foundation                          0x00007fff207f9200 -[NSOperation start] + 785
13  Foundation                          0x00007fff207fd947 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
14  Foundation                          0x00007fff207fd46a __NSOQSchedule_f + 182
15  libdispatch.dylib                   0x000000010635e2c5 _dispatch_block_async_invoke2 + 83
16  libdispatch.dylib                   0x000000010634f74e _dispatch_client_callout + 8
17  libdispatch.dylib                   0x0000000106352066 _dispatch_continuation_pop + 557
18  libdispatch.dylib                   0x000000010635147b _dispatch_async_redirect_invoke + 770
19  libdispatch.dylib                   0x00000001063611b0 _dispatch_root_queue_drain + 351
20  libdispatch.dylib                   0x0000000106361b0f _dispatch_worker_thread2 + 135
21  libsystem_pthread.dylib             0x00007fff60340417 _pthread_wqthread + 244
22  libsystem_pthread.dylib             0x00007fff6033f42f start_wqthread + 15
2021-06-21 18:01:24.916817-0500 ***** *****[6701:2996419] [reports] Main Thread Checker: UI API called on a background thread: -[UITextView text]
PID: 6701, TID: 2996419, Thread name: (none), Queue name: NSOperationQueue 0x7f8685ca3840 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   ***** *****                        0x0000000104fdfbba $s12LocalConsole9LCManagerC5printyyypFSSyXEfU_ + 202
5   ***** *****                        0x0000000104fdf9f9 $s12LocalConsole9LCManagerC5printyyypF + 665
6   ***** *****                        0x0000000104ae715b $s10CloudyLogs6LoggerC3log_4typeySS_ypSgtFZ + 235
7   ***** *****                        0x0000000104edeb3d $s6Shared6*****O13CommunicationEADC14attemptToQueue7channelSo16NSBlockOperationCSgAE7ChannelO_tFyycfU2_ + 477
8   ***** *****                        0x0000000104ede7c0 $sIeg_IeyB_TR + 48
9   Foundation                          0x00007fff207fa0be __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
10  Foundation                          0x00007fff207f9fb6 -[NSBlockOperation main] + 98
11  Foundation                          0x00007fff207fcfd2 __NSOPERATION_IS_INVOKING_MAIN__ + 17
12  Foundation                          0x00007fff207f9200 -[NSOperation start] + 785
13  Foundation                          0x00007fff207fd947 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
14  Foundation                          0x00007fff207fd46a __NSOQSchedule_f + 182
15  libdispatch.dylib                   0x000000010635e2c5 _dispatch_block_async_invoke2 + 83
16  libdispatch.dylib                   0x000000010634f74e _dispatch_client_callout + 8
17  libdispatch.dylib                   0x0000000106352066 _dispatch_continuation_pop + 557
18  libdispatch.dylib                   0x000000010635147b _dispatch_async_redirect_invoke + 770
19  libdispatch.dylib                   0x00000001063611b0 _dispatch_root_queue_drain + 351
20  libdispatch.dylib                   0x0000000106361b0f _dispatch_worker_thread2 + 135
21  libsystem_pthread.dylib             0x00007fff60340417 _pthread_wqthread + 244
22  libsystem_pthread.dylib             0x00007fff6033f42f start_wqthread + 15`

**Comment by moyoteg** [comment]
To solve it 😎:

`        DispatchQueue.main.async {
            localConsoleManager.print(message)
        }`

**Comment by duraidabdul** [comment]
@moyoteg This is fixed in build 1.5.3! Thanks for the report!

**Comment by moyoteg** [comment]
no problem!!
