### ISSUE TITLE
Light and Dark theme for The console widget

### ISSUE THREAD

**Issue by verbose117** [duraidabdul/LocalConsole#7]
It would be awesome if the console widget had a light and dark themes.

**Comment by duraidabdul** [comment]
Great idea! I'll implement this in some way when I get the chance 😃

**Comment by verbose117** [comment]
I am ready to Open a PR

**Comment by duraidabdul** [comment]
Fell free to open a PR if you have extra time, just can't guarantee I'll approve it, I might want to implement it a different way, maybe through the UI with theme options.

**Comment by verbose117** [comment]
I'll Try 🔥

**Comment by haneenmahd** [comment]
Need a Workflow that Builds the App in the command line.
